version: "3"
services:
  db:
    image: postgres:15-bullseye
    networks:
      - expenses
    volumes:
      - "/opt/expenses-postgres-volume:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=expenses
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=Zgfkgvkgft12#$
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: expenses:latest
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - expenses
    ports:
      - "8001:8000"
    volumes:
      - ./source/expenses/:/app
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    image: dpage/pgadmin4:6
    depends_on:
      - db
    networks:
      - expenses
    ports:
      - "5001:80"
    volumes:
      - /opt/expenses-pgadmin-volume:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@dev.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  expenses: