# Generated by Django 4.2 on 2023-04-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reserved_transection_date', models.DateField(verbose_name='date reserved')),
                ('transection_date', models.DateField(verbose_name='action date')),
                ('income', models.DecimalField(decimal_places=7, max_digits=7, verbose_name='income')),
                ('expenses', models.DecimalField(decimal_places=7, max_digits=7, verbose_name='expenses')),
            ],
        ),
    ]
