# Generated by Django 4.2 on 2023-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='transection_date',
            field=models.DateField(),
        ),
    ]
