# Generated by Django 4.2 on 2023-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=7, verbose_name='expenses'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=7, verbose_name='income'),
        ),
    ]
