# Generated by Django 4.2 on 2023-04-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0002_alter_expenses_transection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expenses',
            field=models.DecimalField(decimal_places=7, max_digits=7, verbose_name='expenses'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='income',
            field=models.DecimalField(decimal_places=7, max_digits=7, verbose_name='income'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='reserved_transection_date',
            field=models.DateField(verbose_name='date reserved'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transection_date',
            field=models.DateField(verbose_name='action date'),
        ),
    ]
