# Generated by Django 4.2 on 2023-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0004_alter_expenses_expenses_alter_expenses_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='reserved_transection_date',
            field=models.DateField(blank=True, verbose_name='date reserved'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transection_date',
            field=models.DateField(blank=True, verbose_name='action date'),
        ),
    ]
