# Generated by Django 4.2 on 2023-04-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0005_alter_expenses_reserved_transection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='reserved_transection_date',
            field=models.DateField(default=None, verbose_name='date reserved'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transection_date',
            field=models.DateField(default=None, verbose_name='action date'),
        ),
    ]
