# Generated by Django 4.2 on 2023-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inex', '0006_alter_expenses_reserved_transection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='reserved_expenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='reserved expenses'),
        ),
    ]
